// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	settings "github.com/benjaminbartels/zymurgauge/internal/settings"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type SettingsRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *SettingsRepo) Get() (*settings.Settings, error) {
	ret := _m.Called()

	var r0 *settings.Settings
	if rf, ok := ret.Get(0).(func() *settings.Settings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.Settings)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: c
func (_m *SettingsRepo) Save(c *settings.Settings) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*settings.Settings) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
