// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	auth "github.com/benjaminbartels/zymurgauge/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *UserRepo) Get() (*auth.User, error) {
	ret := _m.Called()

	var r0 *auth.User
	if rf, ok := ret.Get(0).(func() *auth.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: u
func (_m *UserRepo) Save(u *auth.User) error {
	ret := _m.Called(u)

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
