---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.go"
  - "**.js"
  - "**.md"
  - "**.vue"
exclude_paths:
  - "vendor/"
  - "**/ui/build/"
  - "**/ui/config/"
  - "**/ui/README.md"