run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ifshort
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest 
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - exhaustivestruct          # Not recommended globally
    - godox                     # Need to be able to commit code with TODO
linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .NewRequestError(       # used in create RequestError
  gomnd:
    settings:
      mnd:
        ignored-functions: strconv.ParseFloat,make
  gosec:
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go           # Exclude some linters from running on tests files.
      linters:
        - funlen                # Tests are long sometimes
        - goerr113              # Tests can return dynamic errors
        - ifshort               # 'expected' variables don't need use short syntax
    - linters:              
        - lll                   # Exclude lll issues for long lines with go:generate
      source: "^//go:generate "
  # include:
  #   - EXC0002                   # disable excluding of issues about comments from golint
