---
run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - ui
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - depguard                  # Unnecessary
    - godox                     # Need to be able to commit code with TODO
    - varnamelen                # Too optionated
linters-settings:
  ireturn:
    allow:
      - error
      - stdlib
      - device.Thermometer
      - device.Hydrometer
      - device.ThermometerAndHydrometer
      - device.Actuator
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - .Wrap(
      - .Wrapf(
      - .NewRequestError( # used in create RequestError
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go # Exclude some linters from running on tests files.
      linters:
        - funlen # Tests are long sometimes
        - goerr113 # Tests can return dynamic errors
        - gochecknoglobals # Tests can have globals
    - source: "^//go:generate "
      linters:
        - lll # Exclude lll issues for long lines with go:generate
      
