// Code generated by mockery v2.9.4. DO NOT EDIT.

package chamber

import (
	context "context"

	batch "github.com/benjaminbartels/zymurgauge/internal/batch"

	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type BatchRepo struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *BatchRepo) GetAll(ctx context.Context) ([]batch.Batch, error) {
	ret := _m.Called(ctx)

	var r0 []batch.Batch
	if rf, ok := ret.Get(0).(func(context.Context) []batch.Batch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]batch.Batch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *BatchRepo) Get(ctx context.Context, id string) (*batch.Batch, error) {
	ret := _m.Called(ctx, id)

	var r0 *batch.Batch
	if rf, ok := ret.Get(0).(func(context.Context, string) *batch.Batch); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batch.Batch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
