---

name: Build React 
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build React
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 17.0.1
        uses: actions/setup-node@v1
        with:
          node-version: ^17.0.1          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build React
        run: make build-react
      - uses: actions/upload-artifact@v2
        with:
          name: ui
          path: web/build
