---
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-ui:
    name: Build React
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 17.0.1
        uses: actions/setup-node@v1
        with:
          node-version: ^17.0.1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build React
        run: make build-react
      - uses: actions/upload-artifact@v3
        with:
          name: ui
          path: ui/build
  build-service:
    name: Build Go
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Download UI artifacts
        uses: actions/download-artifact@v3
        with:
          name: ui
          path: ui/build
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Build Go
        run: make build-go
