---

name: Build
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set Node.js 17.0.1
        uses: actions/setup-node@v1
        with:
          node-version: ^17.0.1
      - name: Build React
        run: |
          yarn --cwd "web" install
          yarn --cwd "web" build
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build Go
        run: go build -v ./...
