---

name: Lint Go
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
needs: [Build React]
jobs:
  golangci:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Download UI artifacts
        uses: actions/download-artifact@v2
        with:
          name: web
      - name: Check out code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
