name: Publish

on:
  push:
    tags:
      - v*

env:
  VERSION: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Node.js 17.0.1
        uses: actions/setup-node@v1
        with:
          node-version: ^17.0.1
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: build/Dockerfile
          platforms: linux/arm64
          build-args:
          tags: |
            ghcr.io/benjaminbartels/zymurgauge:latest
            ghcr.io/benjaminbartels/zymurgauge:${{ github.ref_name }}
