---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test Go
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Generate coverage report
        run: make coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./profile.cov
          flags: unittests
          name: codecov-umbrella
